repos:
  - repo: local
    hooks:
    - id: stylua
      name: StyLua
      entry: stylua
      language: system
      types:
        - lua
    - id: luacheck
      name: luacheck
      entry: luacheck
      language: system
      types:
        - lua
